### ISSUE TITLE
code sound wrong

### ISSUE THREAD

**Issue by LinuxpowerLudo** [angelmarine/portfolio-deep-learning#1]
Hello,
I think that your code is wrong.
In your test_data you include future data so the prediction is biased.
Regards
Ludo.

**Comment by angelmarine** [comment]
Dear Ludo,

Thank you for raising the issue.
I think you are talking about START_DATE and END_DATE in the train.py.

```python3
# Initialize Dates
START_DATE = '2015-07-06'
END_DATE = '2018-05-28'

# Initialize Model
lstm = LstmModel(name='Old2')
```
So we have two backtest dates (2018-01-01 to 2018-05-29 && 2018-06-01 to 2018-12-30) and we trained two different LSTM models for the different backtest dates. The code above should be for the latter backtest dates (2018-06-01 to 2018-12-30), so it would not intersect with the backtest dates and predictions should not have bias. 

Sorry for the confusion.
Hope my comments made it clear.
